task: gsm8k_checked
dataset_path: openai/gsm8k
dataset_name: main
dataset_kwargs:
  revision: 740312add88f781978c0658806c59bc2815b9866
output_type: generate_until
training_split: train
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
process_results: !function utils.process_results
fewshot_config:
  sampler: first_n
  samples: !function utils.fewshot_samples
num_fewshot: 4
repeats: 1
generation_kwargs:
  until:
    - "Question:"
    - "<|im_end|>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 4096
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: boxed_rate
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
